
GET http://localhost:8080/aliexpress?product=yoga mat
Content-Type: application/json
###

GET http://localhost:8080/ebay?product=Levitating Plant Pot
Content-Type: application/json

###

GET http://localhost:8080/ebayMock
Content-Type: application/json


